description: "Moqume - https://moqu.me"
author: Moqume

defaultTheme: auto
disableThemeToggle: false
ShowShareButtons: true
ShowReadingTime: true
displayFullLangName: true
ShowPostNavLinks: true
ShowBreadCrumbs: true
ShowCodeCopyButtons: true
ShowRssButtonInSectionTermList: true
ShowToc: true
hideFooter: true

profileMode:
  enabled: true
  title: "Hi there!ðŸ‘‹"
  subtitle: >
    My real name is Mike Green, and I'm usually somewhere in or around London, UK.


    My bio in short: I keep servers happy. I program too. Blunt and direct. Asks awkward questions.
  imageUrl: "/assets/images/melofi_300x300.webp"
  imageTitle: "It's me, Moqume!"

socialIcons:
  - name: github
    url: "https://github.com/Moqume"
  - name: mastodon
    url: "https://techhub.social/@moqume"
  - name: medium
    url: "https://medium.com/moqume"
  - name: Rss
    url: "index.xml"
